[settings]
solutions = 500000

[preferred]
1 = ["2", "3", "5"]
2 = ["1", "6", "7"]
3 = ["1", "4", "5"]
4 = ["5", "7"]
5 = ["2", "4", "8"]
6 = ["2", "7"]
7 = ["4", "6", "1"]
8 = ["3", "4"]

[unpreferred]
1 = ["6"]
2 = []
3 = ["8"]
4 = ["1", "2"]
5 = ["1"]
6 = []
7 = ["2"]
8 = []
